version: '3.8'

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - db

    environment:
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '5432:5432'

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 2s
      retries: 5